Repository gnuradio/volk, pull requests merged in 2019-10, with the labels that each got.

#289 bug fixes for volk_32f_index_max_{16,32}u
  kernels/volk/volk_32f_index_max_16u.h
  kernels/volk/volk_32f_index_max_32u.h
Labels: bug, question

#274 Adds neonv7 for volk_16ic_magnitude_16i
  kernels/volk/volk_16ic_magnitude_16i.h
Labels: ARM / Neon, Enhancement

#276 Adds neonv7 to volk_32fc_index_max_32u
  kernels/volk/volk_32fc_index_max_32u.h
Labels: ARM / Neon, Enhancement

#277 Adds neonv7 for volk_32fc_s32f_power_spectrum_32f
  include/volk/volk_neon_intrinsics.h
  kernels/volk/volk_32fc_s32f_power_spectrum_32f.h
Labels: ARM / Neon, Enhancement

#288 fix for spurious heap buffer overflow
  kernels/volk/volk_8u_x2_encodeframepolar_8u.h
Labels: bug, reviewed

#273 Toolchain stuff
  cmake/Toolchains/arm-linux-gnueabihf.cmake
  cmake/Toolchains/arm_cortex_a15_hardfp_native.cmake
  cmake/Toolchains/arm_cortex_a8_hardfp_native.cmake
  cmake/Toolchains/arm_cortex_a8_softfp_native.cmake
  cmake/Toolchains/arm_cortex_a9_hardfp_native.cmake
  lib/CMakeLists.txt
Labels: ARM / Neon, reviewed
