Repository gnuradio/volk, pull requests merged in 2019-11, with the labels that each got.

#302 Add __clang__ specific attributes
  include/volk/volk_common.h
Labels: Enhancement

#291 kernels: add volk_32fc_x2_s32fc_multiply_conjugate_32fc
  kernels/volk/volk_32fc_x2_s32fc_multiply_conjugate_add_32fc.h
  lib/kernel_tests.h
Labels: ARM / Neon, CLA, Enhancement

#309 travis: Add native tests on arm64, s390x and ppc64le architectures
  .travis.yml
Labels: CLA, Enhancement, question, reviewed
